### ISSUE TITLE
I‘d like to know how you got the features?

### ISSUE THREAD

**Issue by mikuzhangping** [CryoliteZ/Video2Text#1]
I just started learning machine learning. You said that getting features through VGG, I really don't know how to achieve it. And I don't know the structure of your features.
Which VGG model do you use.

**Comment by alvinbhou** [comment]
Hi, sorry for the late response. This project is based on one of the assignment in the course "Applied Deep Learning" at NTU. The MSVD data ([Download](https://drive.google.com/file/d/0B18IKlS3niGFNlBoaHJTY3NXUkE/view)) is provided by the TAs.

 If you download the dataset and have a quick glance at the video features

```python
import numpy as np
f = np.load('data/training_data/feat/filename.avi.npy')
f.shape # (80, 4096)
```

Its a video that contains 80 frames, and for each timestep its a 4096-D vector. These feature vectors are obtained by feeding each frame into a Convolutional Network. We sometime call these features as [CNN codes](http://cs231n.github.io/transfer-learning/) (see the part about using ConvNet as fixed feature extractor).

I'm not sure which model the TA used for feature extraction, but you can get similar results using a CNN as a feature extractor (whether its VGG, ResNet or AlexNet). 

[Here](https://medium.com/@franky07724_57962/using-keras-pre-trained-models-for-feature-extraction-in-image-clustering-a142c6cdf5b1) is another article about using pre-trained models for feature extraction. You could take a look if your interested. Hope this helps! 

Edit: I will close this issue due to inactivity, if you have any questions feel free to reopen it.
